---
- name: converge
  hosts: all
  tasks:
    - name: Get OPNsense version
      puzzle.opnsense.get_opnsense_version:
      register: opnsense_version_result

    - name: Display OPNsense version
      debug:
        var: opnsense_version_result.opnsense_version

    - ansible.builtin.assert:
        that: opnsense_version_result.opnsense_version is match('^OPNsense \\d+\\.\\d+(\\s+\\(.+\\))?$')